title: l1dge's blog
email: techiel1dgeatgmaildotcom
description: The new home for my technology journey for the foreseeable future. Always a work in progress.....
baseurl: ""
url: "https://l1dge.github.io"
twitter_username: l1dge
github_username: l1dge

# Build settings
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
  - jekyll-seo

author:
  name: l1dge
  email: techiel1dgeatgmaildotcom
  url: "https://l1dge.github.io"

paginate: 5
owner: l1dge
year: 2021

excerpt_separator: <!--excerpt-end-->

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
